collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7082993
  brandStrength: 0.8727599
  lightness: 0.7627714
  brandColors:
    - '#1E1F16'
    - '#6D4C4B'
    - '#B3E0F9'
    - '#F9C5A4'
    - '#0191F2'
  rhythmicContrast: 0.801268
typography_spectrum: 0.6523297
layout_spectrum: 0.6792115
name: Spangard
